version: '2'

services:

  nextcloud:
    build:
      context: ./nextcloud
    image: iamjavadali/nextcloudpi
    container_name: nextcloud
    restart: unless-stopped
    links:
      - nextcloud_db
    ports:
      - 8080:80 #You can change port 8080 to any avaiable port on your network.   
    volumes:
      - nextcloud:/var/www/html

  nextcloud_db:
    build:
      context: ./mysql
    image: iamjavadali/nextcloudpidb
    container_name: nextcloud_db
    restart: always
    volumes:
      - nextcloud_db:/var/lib/mysql
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW

  nextcloud_redis:
    image: "redis:alpine"
    container_name: nextcloud_redis
    restart: always
    volumes:
      - nextcloud_redis:/data
  
  nextcloud_cron:
    depends_on:
      - nextcloud
    image: iamjavadali/nextcloudpi
    container_name: nextcloud_cron
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh

volumes:
  nextcloud: {}
  nextcloud_db: {}
  nextcloud_redis: {}
  