FROM jc21/nginx-proxy-manager:latest

LABEL "Project"="Nginx Proxy Manager Pi"
LABEL "Author"="Javad Ali"

ENV DB_MYSQL_HOST="nginxproxymanagerpidb"
ENV DB_MYSQL_USER="admin"
ENV DB_MYSQL_PASSWORD="password" 
ENV DB_MYSQL_NAME="nginxproxymanagerpi"
ENV DB_MYSQL_PORT="3306"
