FROM xavierh/goaccess-for-nginxproxymanager:latest

LABEL "Project"="Nginx Proxy Manager Pi"
LABEL "Author"="Javad Ali"

ENV PUID="0"
ENV PGID="0"
ENV TZ="America/New_York"
ENV SKIP_ARCHIVED_LOGS="false"
ENV BASIC_AUTH="false"
ENV BASIC_AUTH_USERNAME="user"
ENV BASIC_AUTH_PASSWORD="Password"
