FROM yobasystems/alpine-mariadb:latest

LABEL "Project"="Nginx Proxy Manager Pi"
LABEL "Author"="Javad Ali"

ENV MYSQL_DATABASE="nginxproxymanagerpi"
ENV MYSQL_USER="admin"
ENV MYSQL_PASSWORD="password"
ENV MYSQL_ROOT_PASSWORD="rootpassword"
