version: '3.8'

services:

  nginxproxymanagerpi:
    build:
      context: ./nginxproxymanager
    image: iamjavadali/nginxproxymanagerpi
    container_name: nginxproxymanagerpi
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"  # You can change port 81 to any available port on your network.
    volumes:
      - nginxproxymanagerpi:/data
      - /var/lib/docker/volumes/nginx-proxy-manager_nginxproxymanagerpi/_data/letsencrypt:/etc/letsencrypt
    depends_on:
      - nginxproxymanagerpidb
      - nginxproxymanagerpistats
    environment:
      DB_MYSQL_HOST: nginxproxymanagerpidb
      DB_MYSQL_USER: admin
      DB_MYSQL_PASSWORD: password
      DB_MYSQL_NAME: nginxproxymanagerpi
      DB_MYSQL_PORT: 3306

  nginxproxymanagerpidb:
    build:
      context: ./mariadb
    image: iamjavadali/nginxproxymanagerpidb
    container_name: nginxproxymanagerpidb
    restart: unless-stopped
    volumes:
      - nginxproxymanagerpidb:/var/lib/mysql

  nginxproxymanagerpistats:
    build:
      context: ./goaccess
    image: iamjavadali/nginxproxymanagerpistats
    container_name: nginxproxymanagerpistats
    restart: unless-stopped
    ports:
      - "7880:7880"
    volumes:
      - /var/lib/docker/volumes/nginx-proxy-manager_nginxproxymanagerpi/_data/logs:/opt/log:ro

volumes:
  nginxproxymanagerpi: {}
  nginxproxymanagerpidb: {}
