FROM mariadb:10.6

LABEL "Project"="NextCloud Pi"
LABEL "Author"="Javad Ali"

ENV MYSQL_DATABASE="nextcloud"
ENV MYSQL_USER="admin"
ENV MYSQL_PASSWORD="password"
ENV MYSQL_ROOT_PASSWORD="rootpassword"
